#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
bgrndrf &			# set the background
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
xset -b
sudo xset s 3600

sudo ifconfig wlp9s0 down

setsid -f weathersync
setsid -f prayersync

betterdiscordctl reinstall || betterdiscordctl install

setsid -f st -e nvim ~/vimwiki/index.wiki

# setsid -f pipewire

# mpd
autostart="picom dunst clipmenud firefox"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

sudo pacman -Sy

#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
# Ensure that xrdb has finished running before moving on to start the WM/DE.
#[ -n "$xrdbpid" ] && wait "$xrdbpid"
