#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
bgrndrf &			# set the background with the `setbg` script

remaps &		# run the remaps script, switching caps/esc and more; check it for more info

xset -b

curl 'wttr.in/Manouba?FTQ1' -s > ~/.weatherreport

curl --output .prayertimes https://api.aladhan.com/v1/timingsByAddress/$(date '+%F')?address=Manouba&method=1

syncthing --no-browser &


#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

autostart="picom dunst pipewire firefox obsidian"

#setsid -f "$TERMINAL" -e cava
# unclutter

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

mpd

# Ensure that xrdb has finished running before moving on to start the WM/DE.
#[ -n "$xrdbpid" ] && wait "$xrdbpid"
